### ISSUE TITLE
--manifest-path argument should point to Cargo.toml, not its directory

### ISSUE THREAD

**Issue by euclio** [steveklabnik/rustdoc#113]
This would make it consistent with the cargo argument.

@steveklabnik, have you considered making an easy issue tag for new contributors? This would be a good candidate.

**Comment by steveklabnik** [comment]
Ugh, I thought that I had made it consistent!

I was thinking that should be help wanted, but maybe easy is a better name

**Comment by mgattozzi** [comment]
@steveklabnik I think having issues ranked from Easy to Hard would be good since it can let people who are newer to rust contribute to low hanging fruit and be grown into consistent contributors while more medium to hard could be tackled by those who know the code base or are at least more experienced with rust (this includes ember to actually since this project is both)

**Comment by euclio** [comment]
Yeah, help-wanted means "we can't figure this out" to me 😆

**Comment by steveklabnik** [comment]
I have made the tag and tagged this easy; if someone wants to tackle this, let us know and we'd be happy to help!

**Comment by mjkillough** [comment]
This seems like a fun first issue! It looks relatively straight-forward, so I'll take a go at implementing something and see how I get on.

**Comment by mgattozzi** [comment]
Awesome! Let us know if you need anything help at all if you get stuck.

**Comment by mjkillough** [comment]
Thanks @mgattozzi! I've had a go at an implementation and opened a PR.
