### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#13]
Right now, there are no tests. We should fix that.

cc https://github.com/steveklabnik/rustdoc/issues/12

**Comment by euclio** [comment]
Is the plan to support htmldocck-style tests, like in the compiler?

**Comment by steveklabnik** [comment]
I would like tests of all kinds, frankly.

**Comment by euclio** [comment]
I'd like to write tests that looks something like the rustdoc tests (bikeshedding aside):

```
#![crate_type = "lib]

//! Crate docs

// @has data.attributes.docs "Crate docs"
```

Is possible to generate and parse save analysis for a single file, without cargo?

**Comment by mgattozzi** [comment]
I think rls-analysis does possibly?  It's already a dep. Considering we output data as JSON we could parse that for information and test for certain things.

**Comment by euclio** [comment]
I'm not very familiar with rls-analysis, but it seems the only implementor of the `AnalysisLoader` trait is `CargoAnalysisLoader`. When I get some time maybe I can lurk on IRC to find out more.

**Comment by steveklabnik** [comment]
> Considering we output data as JSON we could parse that for information and test for certain things.

Yeah, I think this is probably the best way to go for an end-to-end test like this.

As an aside, I'm not sure how useful rustdoc's existing tests are; rather, most of them test the output, which would be ember tests in this case.

Backend tests would be more like "this relationship ends up in the JSON properly" and "this data ends up in the JSON properly", that kind of thing.

**Comment by euclio** [comment]
I think that running against the example crate would be good for a few end-to-end tests.

But, it would get incredibly unwieldy to try and test every individual case inside a single crate, so I'd like to try and emulate the rustdoc model of testing. It should be possible to specify input and output in the same file (without having to make a Cargo.toml, etc.), and allow the cases to be as focused as possible. We could keep each individual cases in a folder, and then write an integration test that runs a checker on each of these files.

I agree that it doesn't make sense to test the HTML output on the backend. Perhaps it wasn't clear in my example, but I was trying to demonstrate a test that would test the JSON output. So, like the rustdoc tests, the programmer would specify the output that should be included by writing inline comments. But, unlike the rustdoc tests, she would use JSON Pointer (or some other JSON query language) instead of XPath to encode what should be in the output.

**Comment by steveklabnik** [comment]
Sounds like we're on the same page 👍

**Comment by euclio** [comment]
Ok, did a short test and I believe this is possible with `AnalysisHost::reload` 🎉

**Comment by steveklabnik** [comment]
Now that the test framework has landed, this should just be a part of new PRs 🎊
