### ISSUE TITLE
Amazing CI setup

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#18]
https://github.com/steveklabnik/rustdoc/issues/17 gives us good CI, this ticket is for *great* CI.

We should write a custom lint that checks if anything in `frontend` was modified, and makes sure that the `frontend\dist` folder was also modified. If not, it should fail the build.

**Comment by fflorent** [comment]
So basically the test would be:
 - touch some file in `frontend`
 - check that the corresponding file in `frontend/dist` has been regenerated
 - if OK → success, failure otherwise
?

If so, I am willing to contribute, though I may take some time (need to ramp up my skills on Ember on my own). Is that OK for you?

Florent

**Comment by steveklabnik** [comment]
@fflorent so, if we merge https://github.com/steveklabnik/rustdoc/pull/36, this problem just goes away; as such, maybe holding off is the right call!

Thanks for being interested in this, maybe I can find another bug that interests you 😄

**Comment by fflorent** [comment]
> Thanks for being interested in this, maybe I can find another bug that interests you 😄

I may have an issue in nom that will take most of my spare time soon :).

Florent
