### ISSUE TITLE
Rustdoc binary can't be used from another directory

### ISSUE THREAD

**Issue by euclio** [steveklabnik/rustdoc#193]
This was causing travis to fail.

Steps to reproduce:

```sh
$ cargo build --all && cd example
$ ../target/debug/rustdoc build
../target/debug/rustdoc build
dyld: Library not loaded: @rpath/libproc_macro-43331b443288c8a7.dylib
  Referenced from: /Users/euclio/repos/rustdoc/example/../target/debug/rustdoc
  Reason: image not found
zsh: abort      ../target/debug/rustdoc build
```

A similar message appears on Linux as well. It's fixable by setting {DY,}LD_LIBRARY_PATH, but we should figure out the root cause so those environment variables don't have to be set.

**Comment by mgattozzi** [comment]
Augh, okay so I got bit by this with my library [curryrs](https://github.com/mgattozzi/curryrs). The problem has to do with Cargo. They made a change a while back to not set the LD_LIBRARY_PATH for files lying outside the default places like /usr. It then becomes the users responsibility to either set that or bundle up the dylib to be in the place where the executable is.

This was never the case before with Cargo around like 1.15 but then they made this change and broke everything. So yeah this only works if LD_LIBRARY_PATH is set and I've not been able to get it set at build time for a lib and it's frustrating.

**Comment by hjr3** [comment]
I did some research as to why this is happening. According to https://github.com/rust-lang/rust/issues/45601, this happens because a dependency is using the `proc_macro` crate. I see this being done in [serde-derive](https://github.com/serde-rs/serde/blob/f218f4d7bfd54c97745a8800170ded4952563a4c/serde_derive/src/lib.rs#L39). As you may know, `serde-derive` is required for `#[derive(Serialize, Deserialize)]` to be used with structs and enums in this crate. Currently, `src/json/api.rs` is using that to create the JSON-API output.
