### ISSUE TITLE
Redirect to the first crate

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#38]
Right now, a footgun is that you have to go to `index.html#/example` to see the example. There's nothing but a blank page on the index.

We should unconditionally redirect to `/example` and then, when https://github.com/steveklabnik/rustdoc/issues/30 is fixed, redirect to the primary crate.

**Comment by somebrel** [comment]
I would like to work on this

**Comment by steveklabnik** [comment]
@somebrel that'd be great! Please let me know if you need any help here.

**Comment by somebrel** [comment]
@steveklabnik 156fc20639d6bae362e0a8b64bdde6f5ebb316fb seems to do the trick but this is my first time using ember, therefore I am not sure if this is the right place/way to do it. 😺

**Comment by steveklabnik** [comment]
@somebrel that looks about right, except

> Transition into another route while replacing the current URL, if possible. This will replace the current history entry instead of adding a new one. Beside that, it is identical to transitionTo in all other respects. See 'transitionTo' for additional information regarding multiple models.

I *think* that we want `transitionTo`, as it's closer to a redirect, but I'm not 100% sure. @locks , any guidance here?

**Comment by locks** [comment]
@steveklabnik I think the behaviour if the desired one, because with a `transitionTo`, when you click the back button you would go to the root of the application, which would then redirect you back to the example.

It seems however to be in the wrong place, because this will trigger whenever you enter the application, meaning you'll always get redirected to the target path.
If you want to only redirect index, move the `beforeModel` hook to that route :)
It is generally advised to transition using the route name, like so: `this.replaceWith('crates',  docsData.data.id);`.

@somebrel let me know if any of the above didn't quite make sense. You can reach me here, on the Mozilla IRC network, or the Ember Slack group!

**Comment by somebrel** [comment]
> It seems however to be in the wrong place, because this will trigger whenever you enter the application, meaning you'll always get redirected to the target path.

Ops! I was able to reproduce this behaviour and yeah... It is not what we want. 😄 

>  If you want to only redirect index, move the beforeModel hook to that route :)

We didn't have an `index` route, so I created one and moved the `beforeModel` hook there and it works! Since the data is already in the `store` at this point (because it was fetched and pushed to the store by the `application` route) I used `this.get('store').peekAll('crate').objectAt(0).id` to acced the id of the crate. What do you guys think about this?

```javascript
// frontend/app/routes/index.js
import Ember from 'ember';

export default Ember.Route.extend({
  beforeModel() {
    this.replaceWith('/' + this.get('store').peekAll('crate').objectAt(0).id);
  },
});
```
Now I have doubts about the way that we acces the name of the main crate: `this.get('store').peekAll('crate').objectAt(0).id`. It does work, but what dou you guys think about this?

**Comment by locks** [comment]
> What do you guys think about this?

@somebrel `this.replaceWith('crates', this.get('store').peekAll('crate').objectAt(0));` ;)
This way we use the route name, and by passing the record itself we skip the model hooks of the `crates` route.

> By the way, I just pushed that one file to my fork and it seems to work. After what kind of change do we have to push frontend/dist/?

I'll leave this one for @steveklabnik, as I haven't familiarized myself with the project yet.

**Comment by mgattozzi** [comment]
If you make changes to the frontend at all you'll need to update the code in `frontend/dist` so that `rustdoc` when built can pull in those assets. Basically if you make any changes to the frontend your PR will need to update `frontend/dist` until some solution is found for #52

**Comment by steveklabnik** [comment]
Doing that update is basically running
```bash
cd frontend
rm -rf dist
npm run prod
```

And then commit the result.
inside of `frontend`

**Comment by somebrel** [comment]
alright, thanks @steveklabnik @locks @mgattozzi doing a PR soon

**Comment by mgattozzi** [comment]
Awesome! Looking forward to it!
